apiVersion: agent.dev/v1
kind: Agent
metadata:
  name: data-analyzer
  version: 1.0.0
  description: Intelligent data analysis with visualization and pattern recognition
  author: Agent as Code Team
  tags:
    - data-analysis
    - statistics
    - visualization
spec:
  runtime: python
  model:
    provider: openai
    name: gpt-4
    config:
      temperature: 0.1
      max_tokens: 1500
      top_p: 0.8
  capabilities:
    - data-analysis
    - statistical-analysis
    - data-visualization
    - pattern-recognition
  dependencies:
    - openai==1.0.0
    - fastapi==0.104.0
    - uvicorn==0.24.0
    - pydantic==2.5.0
    - pandas==2.0.0
    - numpy==1.24.0
    - matplotlib==3.7.0
    - seaborn==0.12.0
    - plotly==5.17.0
    - scipy==1.11.0
    - scikit-learn==1.3.0
    - python-multipart==0.0.6
  environment:
    - name: OPENAI_API_KEY
      from: secret
    - name: LOG_LEVEL
      value: INFO
    - name: MAX_ROWS
      value: "10000"
    - name: CHART_FORMAT
      value: png
  ports:
    - container: 8080
      host: 8080
      protocol: tcp
  healthCheck:
    command: ["curl", "-f", "http://localhost:8080/health"]
    interval: 30s
    timeout: 10s
    retries: 3
    startPeriod: 5s
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi